ALTER TYPE "UxEventName" ADD VALUE IF NOT EXISTS 'VAULT_STORY_OPENED';
ALTER TYPE "UxEventName" ADD VALUE IF NOT EXISTS 'VAULT_STORY_OPEN_FAILED';
ALTER TYPE "UxEventName" ADD VALUE IF NOT EXISTS 'VAULT_COLLECTION_ACTIONS_OPENED';
