DO $$
BEGIN
  CREATE TYPE "StoryGameMode" AS ENUM ('TRAIL_LINEAR');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TYPE "UxEventName" ADD VALUE 'STORY_GAME_ROOM_OPENED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TYPE "UxEventName" ADD VALUE 'STORY_GAME_ACTION_SELECTED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TYPE "UxEventName" ADD VALUE 'STORY_GAME_STEP_SAVED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TYPE "UxEventName" ADD VALUE 'STORY_GAME_STEP_FAILED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TYPE "UxEventName" ADD VALUE 'STORY_GAME_FALLBACK_CLASSIC';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Story"
  ADD COLUMN IF NOT EXISTS "gameMode" "StoryGameMode" NOT NULL DEFAULT 'TRAIL_LINEAR',
  ADD COLUMN IF NOT EXISTS "gameSeed" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "gameMapVersion" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "gameMapJson" JSONB;

ALTER TABLE "StoryStep"
  ADD COLUMN IF NOT EXISTS "gameNodeIndex" INTEGER,
  ADD COLUMN IF NOT EXISTS "gameActionKey" TEXT,
  ADD COLUMN IF NOT EXISTS "gameActionLabel" TEXT;

CREATE INDEX IF NOT EXISTS "StoryStep_storyId_gameNodeIndex_idx"
  ON "StoryStep"("storyId", "gameNodeIndex");
