DO $$
BEGIN
  ALTER TYPE "UxEventName" ADD VALUE 'AUTH_REFRESH_SUCCESS';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TYPE "UxEventName" ADD VALUE 'AUTH_REFRESH_FAILED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
