ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "avatarPresetKey" TEXT NOT NULL DEFAULT 'guardian',
  ADD COLUMN IF NOT EXISTS "avatarVariant" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "avatarAccent" TEXT NOT NULL DEFAULT 'amber';

ALTER TABLE "ChildProfile"
  ADD COLUMN IF NOT EXISTS "avatarPresetKey" TEXT NOT NULL DEFAULT 'guardian',
  ADD COLUMN IF NOT EXISTS "avatarVariant" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "avatarAccent" TEXT NOT NULL DEFAULT 'amber';

ALTER TYPE "UxEventName" ADD VALUE IF NOT EXISTS 'GAME_HOME_OPENED';
ALTER TYPE "UxEventName" ADD VALUE IF NOT EXISTS 'ADVENTURE_RESUME_CLICKED';
ALTER TYPE "UxEventName" ADD VALUE IF NOT EXISTS 'AVATAR_EDITOR_OPENED';
ALTER TYPE "UxEventName" ADD VALUE IF NOT EXISTS 'AVATAR_SAVED';
ALTER TYPE "UxEventName" ADD VALUE IF NOT EXISTS 'CONTENT_FALLBACK_USED';
